cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
    <!-- breadcrum -->
    <div class="py-4 container flex gap-3 items-center">
      <a href="/" class="text-primary text-base">
          <i class="fas fa-home"></i>
      </a>
      <span class="text-sm text-gray-400"><i class="fas fa-chevron-right"></i></span>
      <p class="text-gray-600 font-medium uppercase">Shopping Cart</p>
  </div>
  <!-- breadcrum end -->

  <!-- cart wrapper -->
  <div class="container lg:grid grid-cols-12 gap-6 items-start pb-16 pt-4">
      <!-- product cart -->
      <div class="xl:col-span-9 lg:col-span-8">
          <!-- cart title -->
          <div class="bg-gray-200 py-2 pl-12 pr-20 xl:pr-28 mb-4 hidden md:flex">
              <p class="text-gray-600 text-center">Product</p>
              <p class="text-gray-600 text-center ml-auto mr-16 xl:mr-24">Quantity</p>
              <p class="text-gray-600 text-center">Total</p>
          </div>
          <!-- cart title end -->

          <!-- shipping carts -->
          <div class="space-y-4">
            {% for item in cart %}
              {% with product=item.product %}
              <!-- single cart -->
              <div
                  class="flex items-center md:justify-between gap-4 md:gap-6 p-4 border border-gray-200 rounded flex-wrap md:flex-nowrap">
                  <!-- cart image -->
                  <div class="w-32 flex-shrink-0">
                      <img src="{% if product.image %}{{ product.image.url }}
                      {% else %}{% static "img/no_image.png" %}{% endif %}" class="w-full">
                  </div>
                  <!-- cart image end -->
                  <!-- cart content -->
                  <div class="md:w-1/3 w-full">
                      <h2 class="text-gray-800 mb-3 xl:text-xl textl-lg font-medium uppercase">
                        {{ product.name }}
                      </h2>
                      <p class="text-primary font-semibold">€{{ item.price }}</p>
                      <p class="text-gray-500">Rating: {{ product.get_rating }}</p>
                  </div>
                  <!-- cart content end -->
                  <!-- cart quantity -->
                  <div class="flex border border-gray-300 text-gray-600 divide-x divide-gray-300">
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
                      {{ item.update_quantity_form.quantity }}
                      {{ item.update_quantity_form.override }}
                      <input type="submit" class="font-semibold text-xs hover:text-blue-800" value="Update">
                      {% csrf_token %}
                    </form>
                  </div>
                  <!-- cart quantity end -->
                  <div class="ml-auto md:ml-0">
                      <p class="text-primary text-lg font-semibold">€{{ item.total_price }}</p>
                  </div>
                    <div class="text-gray-600 hover:text-primary cursor-pointer">     
                      <form action="{% url "cart:cart_remove" product.id %}" method="post">        
                        <input type="submit" value="Remove">
                        {% csrf_token %}    
                      </form>  
                    </div>
              </div>
              <!-- single cart end -->
              {% endwith %}
            {% endfor %}
          </div>
          <!-- shipping carts end -->
      </div>
      <!-- product cart end -->
      <!-- order summary -->
      <div class="xl:col-span-3 lg:col-span-4 border border-gray-200 px-4 py-4 rounded mt-6 lg:mt-0">
          <h4 class="text-gray-800 text-lg mb-4 font-medium uppercase">ORDER SUMMARY</h4>
          <div class="space-y-1 text-gray-600 pb-3 border-b border-gray-200">
              <div class="flex justify-between font-medium">
                  <p>Subtotal</p>
                  <p>€{{ cart.get_total_price }}</p>
              </div>
              <div class="flex justify-between">
                  <p>Delivery</p>
                  <p>Free</p>
              </div>
              <div class="flex justify-between">
                  <p>Tax</p>
                  <p>Free</p>
              </div>
          </div>
          <div class="flex justify-between my-3 text-gray-800 font-semibold uppercase">
              <h4>Total</h4>
              <h4>{% if cart.coupon %}
                <tr class="subtotal">
                  <td>Subtotal</td>
                  <td colspan="4"></td>
                  <td class="num">€{{ cart.get_total_price|floatformat:2 }}</td>
                </tr>
                <tr>
                  <td>
                    "{{ cart.coupon.code }}" coupon
                    ({{ cart.coupon.discount }}% off)
                  </td>
                  <td colspan="4"></td>
                  <td class="num neg">
                    - €{{ cart.get_discount|floatformat:2 }}
                  </td>
                </tr>
              {% endif %}
              <tr class="total">
                <td colspan="4"></td>
                <td class="num">
                  €{{ cart.get_total_price_after_discount|floatformat:2 }}
                </td>
              </tr></h4>
          </div>

          <!-- searchbar -->
          <div class="flex mb-5">
            <form action="{% url "coupons:apply" %}" method="post">
              {{ coupon_apply_form }}
              <button type="submit"
                  class="bg-primary border border-primary text-white px-5 font-medium rounded-r-md hover:bg-transparent hover:text-primary transition text-sm font-roboto">
                  Apply
              </button>
              {% csrf_token %}
            </form>
          </div>
          <!-- searchbar end -->

          <!-- checkout -->
          <a href="{% url "orders:order_create" %}" class="bg-primary border border-primary text-white px-4 py-3 font-medium rounded-md uppercase hover:bg-transparent
           hover:text-primary transition text-sm w-full block text-center">
              Process to checkout
          </a>
          <!-- checkout end -->
      </div>
      <!-- order summary end -->
  </div>
  <!-- cart wrapper end -->
{% endblock %}