cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

from shop.views import product_list, product_detail, signup, myaccount, edit_myaccount, search, add_to_wishlist, wishlist, myaddress
app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='shop/user/login.html'), name='login'),
    path('change_password/', views.PasswordChangeView.as_view(template_name='shop/user/change_password.html', success_url=reverse_lazy('password_change_done')), name='password_change'),
    path('password_change_done/', views.PasswordChangeDoneView.as_view(template_name='shop/user/password_change_done.html'), name='password_change_done'),
    path('reset_password', views.PasswordResetView.as_view(template_name='shop/user/reset_password.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='shop/user/password_reset_done.html'), name='password_reset_done'),
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('search', search, name='search'),
    path('wishlist/add_to_wishlist/<int:id>', add_to_wishlist, name='user_wishlist'),
    path("myaccount/wishlist", wishlist, name="wishlist"),
    path("myaccount/myaddress", myaddress, name="myaddress"),

]

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_rating(self):
        reviews_total = 0

        for review in self.reviews.all():
            reviews_total += review.rate

        if reviews_total > 0:
            return reviews_total / self.reviews.count()

        return 0

    def review_count(self):
        count = 0

        for review in self.reviews.all():
            count += 1
        
        return count

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.name

class Address(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = PhoneNumberField()
    country = CountryField()
    address_line = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255)
    town_city = models.CharField(max_length=150)
    postcode = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return "Address"


class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE, related_name='reviews')
    comment=models.TextField()
    rate=models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from .models import Category, Product, Review, Address

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'shop/user/signup.html', {'form': form}) 

@login_required
def myaccount(request):
    return render(request, 'shop/account/myaccount.html')

@login_required
def edit_myaccount(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.username = request.POST.get('username')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/edit_myaccount.html')

@login_required
def myaddress(request):
    return render(request, 'shop/account/myaddress.html')

@login_required
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user)
    return render(request, "shop/account/user_wish_list.html", {"wishlist": products})

@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.name + " has been removed from your WishList")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.name + " to your WishList")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

@login_required
def edit_address(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.phone = request.POST.get('phone')
        user.country = request.POST.get('country')
        user.address_line = request.POST.get('address_line')
        user.address_line2 = request.POST.get('address_line2')
        user.town_city = request.POST.get('town_city')
        user.postcode = request.POST.get('postcode')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/myaddress.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]
    cart_product_form = CartAddProductForm()
    if request.method == 'POST':
        rate = request.POST.get('rate', 0)
        comment = request.POST.get('comment', '')

        if comment:
            reviews = Review.objects.filter(user=request.user, product=product)

            if reviews.count() > 0:
                review = reviews.first()
                review.rate = rate
                review.comment = comment
                review.save()
            else:
                review = Review.objects.create(
                    product=product,
                    rate=rate,
                    comment=comment,
                    user=request.user
                )

            return redirect(product, id=id, slug=slug)

    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form ,'related':related_products})
    

def search(request):
    if request.method == 'GET':
        k = request.GET.get('k')
        if k:
            products = Product.objects.filter(name__icontains=k) 
            return render(request, 'shop/product/search.html', {'products':products})
        else:
            print("No information to show")
            return render(request, 'shop/product/search.html', {})

shop/templates/shop/user/change_password.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<!-- breadcrum -->
<div class="py-4 container flex gap-3 items-center">
    <a href="/" class="text-primary text-base">
        <i class="fas fa-home"></i>
    </a>
    <span class="text-sm text-gray-400"><i class="fas fa-chevron-right"></i></span>
    <p class="text-gray-600 font-medium uppercase">My Account</p>
    </div>
    <!-- breadcrum end -->
    
    <!-- account wrapper -->
    <div class="container lg:grid grid-cols-12 items-start gap-6 pt-4 pb-16">
    <!-- sidebar -->
    <div class="col-span-3">
        <!-- account profile -->
        <div class="px-4 py-3 shadow flex items-center gap-4">
            <div class="flex-shrink-0">
                <img src="{% static "img/avatar.png" %}"
                    class="rounded-full w-14 h-14 p-1 border border-gray-200 object-cover">
            </div>
            <div>
                <p class="text-gray-600">Hello,</p>
                <h4 class="text-gray-800 capitalize font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            </div>
        </div>
        <!-- account profile end -->
    
        <!-- profile links -->
        <div class="mt-6 bg-white shadow rounded p-4 divide-y divide-gray-200 space-y-4 text-gray-600">
            <!-- single link -->
            <div class="space-y-1 pl-8">
                <a href="account.html" 
                    class="relative text-base font-medium capitalize hover:text-primary transition block text-primary">
                    Manage account
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-address-card"></i>
                    </span>
                </a>
                <a href="{% url 'shop:edit_myaccount' %}" class="hover:text-primary transition capitalize block">Profile
                    information</a>
                <a href="manage-address.html" class="hover:text-primary transition capitalize block">Manage
                    address</a>
                <a href="{% url 'shop:password_change' %}" class="hover:text-primary transition capitalize block">change
                    password</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    My order history
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-gift"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">my returns</a>
                <a href="#" class="hover:text-primary transition block capitalize">my cancellations</a>
                <a href="#" class="hover:text-primary transition block capitalize">my reviews</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    Payment methods
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-credit-card"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">Voucher</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
               <a href="{% url 'shop:wishlist' %}" class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    my wishlist
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-heart"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
                <a href="{% url 'shop:logout' %}"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    logout
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-sign-out-alt"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
        </div>
        <!-- profile links end -->
    </div>
    <!-- sidebar end -->

    <!-- account content -->
    <div class="col-span-9 shadow rounded px-6 pt-5 pb-7 mt-6 lg:mt-0">
        <h3 class="text-lg font-medium capitalize mb-4">
            Change password
        </h3>
        <form method="post" action="{% url 'shop:password_change' %}">
            {% csrf_token %}
            <div class="space-y-4 max-w-sm">
                {% for field in form %}
                <div>
                    <label class="text-gray-600 mb-2 block">
                        {{ field.label }}
                    </label>
                    <div class="relative">
                        <span class="absolute right-3 top-3 text-sm text-gray-500 cursor-pointer">
                            <i class="far fa-eye-slash"></i>
                        </span>
                        <input type="text" class="input-box" placeholder="{{ field.label }}">
                    </div>
                </div>
                {% endfor %}
            </div>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{ error|escape }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                    <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                        <p>{{ error|escape }}</p>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="mt-6">
                <button type="submit"
                    class="px-6 py-2 text-center text-white bg-primary border border-primary rounded hover:bg-transparent hover:text-primary transition uppercase font-roboto font-medium">
                    Save change
                </button>
            </div>
        </form>
    </div>
    <!-- account content end -->
</div>
<!-- account wrapper end -->
{% endblock %}

shop/templates/shop/user/login.html
{% extends "shop/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<script src="https://cdn.tailwindcss.com"></script>
<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
            <p tabindex="0" class="focus:outline-none text-2xl font-extrabold leading-6 text-gray-800">Login to your account</p>
            <p tabindex="0" class="focus:outline-none text-sm mt-4 font-medium leading-none text-gray-500">Dont have account? <a href="{% url 'shop:signup' %}"   class="hover:text-gray-500 focus:text-gray-500 focus:outline-none focus:underline hover:underline text-sm font-medium leading-none  text-gray-800 cursor-pointer"> Sign up here</a></p>
            <button aria-label="Continue with google" role="button" class="focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-gray-700 py-3.5 px-4 border rounded-lg border-gray-700 flex items-center w-full mt-10">
                <svg width="19" height="20" viewBox="0 0 19 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M18.9892 10.1871C18.9892 9.36767 18.9246 8.76973 18.7847 8.14966H9.68848V11.848H15.0277C14.9201 12.767 14.3388 14.1512 13.047 15.0812L13.0289 15.205L15.905 17.4969L16.1042 17.5173C17.9342 15.7789 18.9892 13.221 18.9892 10.1871Z" fill="#4285F4" />
                    <path d="M9.68813 19.9314C12.3039 19.9314 14.4999 19.0455 16.1039 17.5174L13.0467 15.0813C12.2286 15.6682 11.1306 16.0779 9.68813 16.0779C7.12612 16.0779 4.95165 14.3395 4.17651 11.9366L4.06289 11.9465L1.07231 14.3273L1.0332 14.4391C2.62638 17.6946 5.89889 19.9314 9.68813 19.9314Z" fill="#34A853" />
                    <path d="M4.17667 11.9366C3.97215 11.3165 3.85378 10.6521 3.85378 9.96562C3.85378 9.27905 3.97215 8.6147 4.16591 7.99463L4.1605 7.86257L1.13246 5.44363L1.03339 5.49211C0.37677 6.84302 0 8.36005 0 9.96562C0 11.5712 0.37677 13.0881 1.03339 14.4391L4.17667 11.9366Z" fill="#FBBC05" />
                    <path d="M9.68807 3.85336C11.5073 3.85336 12.7344 4.66168 13.4342 5.33718L16.1684 2.59107C14.4892 0.985496 12.3039 0 9.68807 0C5.89885 0 2.62637 2.23672 1.0332 5.49214L4.16573 7.99466C4.95162 5.59183 7.12608 3.85336 9.68807 3.85336Z" fill="#EB4335" />
                </svg>
                <p class="text-base font-medium ml-4 text-gray-700">Continue with Google</p>
            </button>
            <button aria-label="Continue with twitter" role="button" class="focus:outline-none  focus:ring-2 focus:ring-offset-1 focus:ring-gray-700 py-3.5 px-4 border rounded-lg border-gray-700 flex items-center w-full mt-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M22.1623 5.656C21.3989 5.9937 20.5893 6.21548 19.7603 6.314C20.634 5.79144 21.288 4.96902 21.6003 4C20.7803 4.488 19.8813 4.83 18.9443 5.015C18.3149 4.34158 17.4807 3.89497 16.5713 3.74459C15.6618 3.59421 14.7282 3.74849 13.9156 4.18346C13.1029 4.61842 12.4567 5.30969 12.0774 6.1498C11.6981 6.9899 11.607 7.93178 11.8183 8.829C10.1554 8.74566 8.52863 8.31353 7.04358 7.56067C5.55854 6.80781 4.24842 5.75105 3.1983 4.459C2.82659 5.09745 2.63125 5.82323 2.6323 6.562C2.6323 8.012 3.3703 9.293 4.4923 10.043C3.82831 10.0221 3.17893 9.84278 2.5983 9.52V9.572C2.5985 10.5377 2.93267 11.4736 3.54414 12.2211C4.15562 12.9685 5.00678 13.4815 5.9533 13.673C5.33691 13.84 4.6906 13.8647 4.0633 13.745C4.33016 14.5762 4.8503 15.3032 5.55089 15.8241C6.25147 16.345 7.09742 16.6338 7.9703 16.65C7.10278 17.3313 6.10947 17.835 5.04718 18.1322C3.98488 18.4294 2.87442 18.5143 1.7793 18.382C3.69099 19.6114 5.91639 20.2641 8.1893 20.262C15.8823 20.262 20.0893 13.889 20.0893 8.362C20.0893 8.182 20.0843 8 20.0763 7.822C20.8952 7.23017 21.6019 6.49702 22.1633 5.657L22.1623 5.656Z" fill="#1DA1F2"/>
                    </svg>
                    
                <p class="text-base font-medium ml-4 text-gray-700">Continue with Twitter</p>
            </button>

            <div class="w-full flex items-center justify-between py-5">
                <hr class="w-full bg-gray-400">
                <p class="text-base font-medium leading-4 px-2.5 text-gray-400">OR</p>
                <hr class="w-full bg-gray-400  ">
               </div>

                <form method="post" action="." class="space-y-3 justify-center">
                    {% csrf_token %}

                    <div>
                        <label class="text-gray-600 mb-2 block">E-mail<span class="text-primary">*</span></label>
                        <input type="text" name="username" class="input-box">
                    </div>

                    <div>
                        <label class="text-gray-600 mb-2 block">Password<span class="text-primary">*</span></label>
                        <input type="password" name="password" class="input-box">
                        <div class="absolute right-0 mt-2 mr-3 cursor-pointer">
                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M7.99978 2C11.5944 2 14.5851 4.58667 15.2124 8C14.5858 11.4133 11.5944 14 7.99978 14C4.40511 14 1.41444 11.4133 0.787109 8C1.41378 4.58667 4.40511 2 7.99978 2ZM7.99978 12.6667C9.35942 12.6664 10.6787 12.2045 11.7417 11.3568C12.8047 10.509 13.5484 9.32552 13.8511 8C13.5473 6.67554 12.8031 5.49334 11.7402 4.64668C10.6773 3.80003 9.35864 3.33902 7.99978 3.33902C6.64091 3.33902 5.32224 3.80003 4.25936 4.64668C3.19648 5.49334 2.45229 6.67554 2.14844 8C2.45117 9.32552 3.19489 10.509 4.25787 11.3568C5.32085 12.2045 6.64013 12.6664 7.99978 12.6667ZM7.99978 11C7.20413 11 6.44106 10.6839 5.87846 10.1213C5.31585 9.55871 4.99978 8.79565 4.99978 8C4.99978 7.20435 5.31585 6.44129 5.87846 5.87868C6.44106 5.31607 7.20413 5 7.99978 5C8.79543 5 9.55849 5.31607 10.1211 5.87868C10.6837 6.44129 10.9998 7.20435 10.9998 8C10.9998 8.79565 10.6837 9.55871 10.1211 10.1213C9.55849 10.6839 8.79543 11 7.99978 11ZM7.99978 9.66667C8.4418 9.66667 8.86573 9.49107 9.17829 9.17851C9.49085 8.86595 9.66644 8.44203 9.66644 8C9.66644 7.55797 9.49085 7.13405 9.17829 6.82149C8.86573 6.50893 8.4418 6.33333 7.99978 6.33333C7.55775 6.33333 7.13383 6.50893 6.82126 6.82149C6.5087 7.13405 6.33311 7.55797 6.33311 8C6.33311 8.44203 6.5087 8.86595 6.82126 9.17851C7.13383 9.49107 7.55775 9.66667 7.99978 9.66667Z" fill="#71717A"/>
                                </svg>
                                
                        </div>
                    </div>

                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                                    <p>{{ error|escape }}</p>
                                </div>
                            {% endfor %}
                        {% endfor %}

                        {% for error in form.non_field_errors %}
                            <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                                <p>{{ error|escape }}</p>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <a href="{% url 'shop:password_reset' %}" class="hover:text-gray-500 focus:text-gray-500 focus:outline-none focus:underline hover:underline text-sm font-medium leading-none  text-gray-800 cursor-pointer">
                        Forgot password?
                    </a>
                    <div>
                        <button class="text-white bg-primary border border-primary rounded hover:bg-transparent hover:text-primary transition uppercase font-roboto font-medium py-4 w-full">Submit</button>

                    </div>
                </form>
            </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/user/password_change_done.html
{% extends "shop/base.html" %}

{% block content %}
<div class="mt-5">
    <div class="alert alert-success">
        Password was changed successfully
    </div>
    <a href="/" class="text-blue-500"> Click here to go back to homepage </a>
</div>
{% endblock %}

shop/templates/shop/user/password_reset_done.html
{% extends "shop/base.html" %}

{% block content %}
<div class="mt-5">
    <div class="alert alert-success">
        Check you're email for password reset details
    </div>
    <a href="/" class="text_blue-500"> Click here to go back to homepage </a>
</div>
{% endblock %}

shop/templates/shop/user/reset_password.html
{% extends "shop/base.html" %}

{% block content %}
<div class="max-w-lg mx-auto flex flex-wrap p-6">
    <div class="w-full bg-gray-100 p-6 rounded-xl">
        <h1 class="focus:outline-none text-2xl font-extrabold leading-6 text-gray-800">Reset Password</h1>

        <form method="post" action="{% url 'shop:password_reset' %}" class="space-y-3">
            {% csrf_token %}

            {% for field in form %}
                <div>
                    <label class="text-sm font-medium leading-none text-gray-800">{{ field.label }}</label>
                    <input type="text" name="" class="bg-gray-200 border rounded  text-xs font-medium leading-none text-gray-800 py-3 w-full pl-3 mt-2">
                </div>
            {% endfor %}

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                            <p>{{ error|escape }}</p>
                        </div>
                    {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                    <div class="p-6 bg-red-200 text-red-800 rounded-xl">
                        <p>{{ error|escape }}</p>
                    </div>
                {% endfor %}
            {% endif %}

            <div>
                <button class="focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 text-sm font-semibold leading-none text-white focus:outline-none bg-blue-500 border rounded hover:bg-blue-400 py-4 w-full">Submit</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}