cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

from shop.views import product_list, product_detail, signup, myaccount, edit_myaccount, search, add_to_wishlist, wishlist, myaddress
app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='shop/user/login.html'), name='login'),
    path('change_password/', views.PasswordChangeView.as_view(template_name='shop/user/change_password.html', success_url=reverse_lazy('password_change_done')), name='password_change'),
    path('password_change_done/', views.PasswordChangeDoneView.as_view(template_name='shop/user/password_change_done.html'), name='password_change_done'),
    path('reset_password', views.PasswordResetView.as_view(template_name='shop/user/reset_password.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='shop/user/password_reset_done.html'), name='password_reset_done'),
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('search', search, name='search'),
    path('wishlist/add_to_wishlist/<int:id>', add_to_wishlist, name='user_wishlist'),
    path("myaccount/wishlist", wishlist, name="wishlist"),
    path("myaccount/myaddress", myaddress, name="myaddress"),

]

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_rating(self):
        reviews_total = 0

        for review in self.reviews.all():
            reviews_total += review.rate

        if reviews_total > 0:
            return reviews_total / self.reviews.count()

        return 0

    def review_count(self):
        count = 0

        for review in self.reviews.all():
            count += 1
        
        return count

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.name

class Address(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = PhoneNumberField()
    country = CountryField()
    address_line = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255)
    town_city = models.CharField(max_length=150)
    postcode = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return "Address"


class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE, related_name='reviews')
    comment=models.TextField()
    rate=models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from .models import Category, Product, Review, Address

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'shop/user/signup.html', {'form': form}) 

@login_required
def myaccount(request):
    return render(request, 'shop/account/myaccount.html')

@login_required
def edit_myaccount(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.username = request.POST.get('username')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/edit_myaccount.html')

@login_required
def myaddress(request):
    return render(request, 'shop/account/myaddress.html')

@login_required
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user)
    return render(request, "shop/account/user_wish_list.html", {"wishlist": products})

@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.name + " has been removed from your WishList")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.name + " to your WishList")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

@login_required
def edit_address(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.phone = request.POST.get('phone')
        user.country = request.POST.get('country')
        user.address_line = request.POST.get('address_line')
        user.address_line2 = request.POST.get('address_line2')
        user.town_city = request.POST.get('town_city')
        user.postcode = request.POST.get('postcode')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/myaddress.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]
    cart_product_form = CartAddProductForm()
    if request.method == 'POST':
        rate = request.POST.get('rate', 0)
        comment = request.POST.get('comment', '')

        if comment:
            reviews = Review.objects.filter(user=request.user, product=product)

            if reviews.count() > 0:
                review = reviews.first()
                review.rate = rate
                review.comment = comment
                review.save()
            else:
                review = Review.objects.create(
                    product=product,
                    rate=rate,
                    comment=comment,
                    user=request.user
                )

            return redirect(product, id=id, slug=slug)

    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form ,'related':related_products})
    

def search(request):
    if request.method == 'GET':
        k = request.GET.get('k')
        if k:
            products = Product.objects.filter(name__icontains=k) 
            return render(request, 'shop/product/search.html', {'products':products})
        else:
            print("No information to show")
            return render(request, 'shop/product/search.html', {})

shop/templates/shop/base.html
<!doctype html>
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		    <title>{% block title %}My shop{% endblock %}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <script src="https://unpkg.com/flowbite@1.4.3/dist/flowbite.js"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>
    <body>
      {% include 'shop/navbar.html' %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        {% include 'shop/footer.html' %}

        <script>
            let menuBar = document.querySelector('#menuBar')
            let mobileMenu = document.querySelector('#mobileMenu')
            let closeMenu = document.querySelector('#closeMenu')
    
            menuBar.addEventListener('click', function(){
                mobileMenu.classList.remove('hidden')
            })
    
            closeMenu.addEventListener('click', function(){
                mobileMenu.classList.add('hidden')
            })
        </script>
    </body>
</html>

shop/templates/shop/footer.html
{% load static %}
<!-- footer -->
<footer class="bg-white pt-16 pb-12 border-t border-gray-100">
  <div class="container">
      <div class="xl:grid xl:grid-cols-3 xl:gap-8">
          <!-- footer text -->
          <div class="space-y-8 xl:col-span-1">
              <img class="w-30" src="images/logo.svg" alt="Company name">
              <p class="text-gray-500 text-base">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio facere rem
              </p>
              <div class="flex space-x-6">
                  <a href="#" class="text-gray-400 hover:text-gray-500">
                      <i class="fab fa-facebook-f"></i>
                  </a>
                  <a href="#" class="text-gray-400 hover:text-gray-500">
                      <i class="fab fa-twitter"></i>
                  </a>
                  <a href="#" class="text-gray-400 hover:text-gray-500">
                      <i class="fab fa-instagram"></i>
                  </a>
                  <a href="#" class="text-gray-400 hover:text-gray-500">
                      <i class="fab fa-linkedin-in"></i>
                  </a>
              </div>
          </div>
          <!-- footer text end -->
          <!-- footer links -->
          <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
              <div class="md:grid md:grid-cols-2 md:gap-8">
                  <div>
                      <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                          Solutions
                      </h3>
                      <div class="mt-4 space-y-4">
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Marketing
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Analytics
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Commerce
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Insights
                          </a>
                      </div>
                  </div>
                  <div class="mt-12 md:mt-0">
                      <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                          Support
                      </h3>
                      <div class="mt-4 space-y-4">
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Pricing
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Documentation
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Guides
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              API Status
                          </a>
                      </div>
                  </div>
              </div>
              <div class="md:grid md:grid-cols-2 md:gap-8">
                  <div>
                      <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                          Company
                      </h3>
                      <div class="mt-4 space-y-4">
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              About
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Blog
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Jobs
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Press
                          </a>
                      </div>
                  </div>
                  <div class="mt-12 md:mt-0">
                      <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
                          Legal
                      </h3>
                      <div class="mt-4 space-y-4">
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Claim
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Privacy
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Policy
                          </a>
                          <a href="#" class="text-base text-gray-500 hover:text-gray-900 block">
                              Terms
                          </a>
                      </div>
                  </div>
              </div>
          </div>
          <!-- footer links end -->
      </div>
  </div>
</footer>
<!-- footer end -->

<!-- copyright -->
<div class="bg-gray-800 py-4">
  <div class="container flex items-center justify-between">
      <p class="text-white">© RAFCART - All Rights Reserved</p>
      <div>
          <img src="{% static "img/methods.png" %}" class="h-5">
      </div>
  </div>
</div>
<!-- copyright end -->

shop/templates/shop/navbar.html
{% load static %}
    <header class="py-4 shadow-sm bg-pink-100 lg:bg-white">
      <div class="container flex items-center justify-between">
          <!-- logo -->
          <a href="/" class="block w-32">
              <img src="{% static "img/logo.svg" %}" alt="logo" class="w-full">
          </a>
          <!-- logo end -->

          <!-- searchbar -->
          <form action="/search">
            <div class="w-full xl:max-w-xl lg:max-w-lg lg:flex relative hidden">
              <span class="absolute left-4 top-3 text-lg text-gray-400">
                  <i class="fas fa-search"></i>
              </span>
              <input name="k" type="text"
                  class="pl-12 w-full border border-r-0 border-primary py-3 px-3 rounded-l-md focus:ring-primary focus:border-primary"
                  placeholder="search">
              <button type="submit"
                  class="bg-primary border border-primary text-white px-8 font-medium rounded-r-md hover:bg-transparent hover:text-primary transition">
                  Search
              </button>
            </div>
          </form>
          <!-- searchbar end -->

          <!-- navicons -->
          <div class="space-x-4 flex items-center">
              <a href="{% url 'shop:wishlist' %}" class="block text-center text-gray-700 hover:text-primary transition relative">
                  <span
                      class="absolute -right-0 -top-1 w-5 h-5 rounded-full flex items-center justify-center bg-primary text-white text-xs">{{ wishlist|length }}</span>
                  <div class="text-2xl">
                      <i class="far fa-heart"></i>
                  </div>
                  <div class="text-xs leading-3">Wish List</div>
              </a>
              <a href="{% url 'cart:cart_detail' %}"
                  class="lg:block text-center text-gray-700 hover:text-primary transition hidden relative">
                  <span
                      class="absolute -right-3 -top-1 w-5 h-5 rounded-full flex items-center justify-center bg-primary text-white text-xs">{{ cart|length }}</span>
                  <div class="text-2xl">
                      <i class="fas fa-shopping-bag"></i>
                  </div>
                  <div class="text-xs leading-3">Cart</div>
              </a>
              <a href="{% url 'shop:myaccount' %}" class="block text-center text-gray-700 hover:text-primary transition">
                  <div class="text-2xl">
                      <i class="far fa-user"></i>
                  </div>
                  <div class="text-xs leading-3">Account</div>
              </a>
          </div>
          <!-- navicons end -->

      </div>
  </header>
  <!-- header end -->

  <!-- navbar -->
  <nav class="bg-gray-800 hidden lg:block">
      <div class="container">
          <div class="flex">

              <!-- all category -->
              <div class="px-8 py-4 bg-primary flex items-center cursor-pointer group relative">
                  <span class="text-white">
                      <i class="fas fa-bars"></i>
                  </span>
                  <span class="capitalize ml-2 text-white">All categories</span>
                  <div
                      class="absolute left-0 top-full w-full divide-gray-300 divide-dashed divide-y bg-white shadow-md py-3 invisible opacity-0 group-hover:opacity-100 group-hover:visible transition duration-300 z-50">
                      <!-- single category -->
                      <div {% if not category %}class="selected"{% endif %}>
                        <a href="{% url "shop:product_list" %}" class="px-6 py-3 flex items-center border-gray-300 hover:bg-gray-100 transition">
                          <img src="{% static "img/card-list.svg" %}" class="w-5 h-5 object-contain">
                          <span class="ml-6 text-gray-600 text-sm">All</span>
                        </a>
                      </div>
                      <!-- single category end -->
                      {% for c in categories %}
                      <!-- single category -->
                      <div {% if category.slug == c.slug %}class="selected"{% endif %}>
                        <a href="{{ c.get_absolute_url }}" class="px-6 py-3 flex items-center border-gray-300 hover:bg-gray-100 transition">
                            <img src="{% static "img/card-list.svg" %}" class="w-5 h-5 object-contain">
                            <span class="ml-6 text-gray-600 text-sm">{{ c.name }}</span>
                        </a>
                      </div>
                      <!-- single category end -->
                      {% endfor %}
                  </div>
              </div>
              <!-- all category end -->

              <!-- nav menu -->
              <div class="flex items-center justify-between flex-grow pl-12">
                  <div class="flex items-center space-x-6 text-base capitalize">
                      <a href="/" class="text-gray-200 hover:text-white transition">Home</a>
                      <a href="/" class="text-gray-200 hover:text-white transition">Shop</a>
                      <a href="#" class="text-gray-200 hover:text-white transition">About us</a>
                      <a href="#" class="text-gray-200 hover:text-white transition">Contact us</a>
                  </div>
                  {% if user.is_authenticated %}
                  <a href="{% url "shop:myaccount" %}" class="ml-auto justify-self-end text-gray-200 hover:text-white transition">
                      Hi {{ user.first_name }} {{ user.last_name }}
                  </a>
                  {% else %}
                  <a href="{% url "shop:login" %}" class="ml-auto justify-self-end text-gray-200 hover:text-white transition">
                    Login/Register
                  </a>
                  {% endif %}
              </div>
              <!-- nav menu end -->

          </div>
      </div>
  </nav>
  <!-- navbar end -->

   <!-- mobile menubar -->
   <div
   class="fixed w-full border-t border-gray-200 shadow-sm bg-white py-3 bottom-0 left-0 flex justify-around items-start px-6 lg:hidden z-40">
   <a href="javascript:void(0)" class="block text-center text-gray-700 hover:text-primary transition relative">
       <div class="text-2xl" id="menuBar">
           <i class="fas fa-bars"></i>
       </div>
       <div class="text-xs leading-3">Menu</div>
   </a>
   <a href="" class="block text-center text-gray-700 hover:text-primary transition relative">
       <div class="text-2xl">
           <i class="fas fa-list-ul"></i>
       </div>
       <div class="text-xs leading-3">Category</div>
   </a>
   <a href="#" class="block text-center text-gray-700 hover:text-primary transition relative">
       <div class="text-2xl">
           <i class="fas fa-search"></i>
       </div>
       <div class="text-xs leading-3">Search</div>
   </a>
   <a href="{% url 'cart:cart_detail' %}" class="text-center text-gray-700 hover:text-primary transition relative">
       <span
           class="absolute -right-3 -top-1 w-5 h-5 rounded-full flex items-center justify-center bg-primary text-white text-xs">3</span>
       <div class="text-2xl">
           <i class="fas fa-shopping-bag"></i>
       </div>
       <div class="text-xs leading-3">Cart</div>
   </a>
</div>
<!-- mobile menu end -->

<!-- mobile sidebar menu -->
<div class="fixed left-0 top-0 w-full h-full z-50 bg-black bg-opacity-30 shadow hidden" id="mobileMenu">
   <div class="absolute left-0 top-0 w-72 h-full z-50 bg-white shadow">
       <div id="closeMenu"
           class="text-gray-400 hover:text-primary text-lg absolute right-3 top-3 cursor-pointer">
           <i class="fas fa-times"></i>
       </div>
       <!-- navlink -->
       <h3 class="text-xl font-semibold text-gray-700 mb-1 font-roboto pl-4 pt-4">Menu</h3>
       <div class="">
           <a href="/" class="block px-4 py-2 font-medium transition hover:bg-gray-100">
               Home
           </a>
           <a href="/" class="block px-4 py-2 font-medium transition hover:bg-gray-100">
               Shop
           </a>
           <a href="#" class="block px-4 py-2 font-medium transition hover:bg-gray-100">
               About Us
           </a>
           <roa href="#" class="block px-4 py-2 font-medium transition hover:bg-gray-100">
               Contact Us
           </roa>
       </div>
       <!-- navlinks end -->
   </div>
</div>
<!-- mobile sidebar menu end -->