cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib.auth import views
from django.urls import path, reverse_lazy

from shop.views import product_list, product_detail, signup, myaccount, edit_myaccount, search, add_to_wishlist, wishlist, myaddress
app_name = 'shop'

urlpatterns = [
    path('', product_list, name='product_list'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='shop/user/login.html'), name='login'),
    path('change_password/', views.PasswordChangeView.as_view(template_name='shop/user/change_password.html', success_url=reverse_lazy('password_change_done')), name='password_change'),
    path('password_change_done/', views.PasswordChangeDoneView.as_view(template_name='shop/user/password_change_done.html'), name='password_change_done'),
    path('reset_password', views.PasswordResetView.as_view(template_name='shop/user/reset_password.html', success_url=reverse_lazy('password_reset_done')), name='password_reset'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(template_name='shop/user/password_reset_done.html'), name='password_reset_done'),
    path('myaccount/', myaccount, name='myaccount'),
    path('myaccount/edit/', edit_myaccount, name='edit_myaccount'),
    path('<slug:category_slug>/', product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_detail'),
    path('search', search, name='search'),
    path('wishlist/add_to_wishlist/<int:id>', add_to_wishlist, name='user_wishlist'),
    path("myaccount/wishlist", wishlist, name="wishlist"),
    path("myaccount/myaddress", myaddress, name="myaddress"),

]

shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django_countries.fields import CountryField
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_rating(self):
        reviews_total = 0

        for review in self.reviews.all():
            reviews_total += review.rate

        if reviews_total > 0:
            return reviews_total / self.reviews.count()

        return 0

    def review_count(self):
        count = 0

        for review in self.reviews.all():
            count += 1
        
        return count

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.name

class Address(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phone = PhoneNumberField()
    country = CountryField()
    address_line = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255)
    town_city = models.CharField(max_length=150)
    postcode = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Address"
        verbose_name_plural = "Addresses"

    def __str__(self):
        return "Address"


class Review(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE, related_name='reviews')
    comment=models.TextField()
    rate=models.IntegerField(default=0)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from cart.forms import CartAddProductForm
from .models import Category, Product, Review, Address

from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request, user)

            return redirect('/')
    else:
        form = SignUpForm()

    return render(request, 'shop/user/signup.html', {'form': form}) 

@login_required
def myaccount(request):
    return render(request, 'shop/account/myaccount.html')

@login_required
def edit_myaccount(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.email = request.POST.get('email')
        user.username = request.POST.get('username')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/edit_myaccount.html')

@login_required
def myaddress(request):
    return render(request, 'shop/account/myaddress.html')

@login_required
def wishlist(request):
    products = Product.objects.filter(users_wishlist=request.user)
    return render(request, "shop/account/user_wish_list.html", {"wishlist": products})

@login_required
def add_to_wishlist(request, id):
    product = get_object_or_404(Product, id=id)
    if product.users_wishlist.filter(id=request.user.id).exists():
        product.users_wishlist.remove(request.user)
        messages.success(request, product.name + " has been removed from your WishList")
    else:
        product.users_wishlist.add(request.user)
        messages.success(request, "Added " + product.name + " to your WishList")
    return HttpResponseRedirect(request.META["HTTP_REFERER"])

@login_required
def edit_address(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.phone = request.POST.get('phone')
        user.country = request.POST.get('country')
        user.address_line = request.POST.get('address_line')
        user.address_line2 = request.POST.get('address_line2')
        user.town_city = request.POST.get('town_city')
        user.postcode = request.POST.get('postcode')
        user.save()

        return redirect('shop:myaccount')
    return render(request, 'shop/account/myaddress.html')


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    related_products=Product.objects.filter(category=product.category).exclude(id=id)[:4]
    cart_product_form = CartAddProductForm()
    if request.method == 'POST':
        rate = request.POST.get('rate', 0)
        comment = request.POST.get('comment', '')

        if comment:
            reviews = Review.objects.filter(user=request.user, product=product)

            if reviews.count() > 0:
                review = reviews.first()
                review.rate = rate
                review.comment = comment
                review.save()
            else:
                review = Review.objects.create(
                    product=product,
                    rate=rate,
                    comment=comment,
                    user=request.user
                )

            return redirect(product, id=id, slug=slug)

    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form ,'related':related_products})
    

def search(request):
    if request.method == 'GET':
        k = request.GET.get('k')
        if k:
            products = Product.objects.filter(name__icontains=k) 
            return render(request, 'shop/product/search.html', {'products':products})
        else:
            print("No information to show")
            return render(request, 'shop/product/search.html', {})

shop/templates/shop/account/edit_myaccount.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Edit account{% endblock %}

{% block content %}
<!-- breadcrum -->
<div class="py-4 container flex gap-3 items-center">
    <a href="/" class="text-primary text-base">
        <i class="fas fa-home"></i>
    </a>
    <span class="text-sm text-gray-400"><i class="fas fa-chevron-right"></i></span>
    <p class="text-gray-600 font-medium uppercase">My Account</p>
    </div>
    <!-- breadcrum end -->
    
    <!-- account wrapper -->
    <div class="container lg:grid grid-cols-12 items-start gap-6 pt-4 pb-16">
    <!-- sidebar -->
    <div class="col-span-3">
        <!-- account profile -->
        <div class="px-4 py-3 shadow flex items-center gap-4">
            <div class="flex-shrink-0">
                <img src="{% static "img/avatar.png" %}"
                    class="rounded-full w-14 h-14 p-1 border border-gray-200 object-cover">
            </div>
            <div>
                <p class="text-gray-600">Hello,</p>
                <h4 class="text-gray-800 capitalize font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            </div>
        </div>
        <!-- account profile end -->
    
        <!-- profile links -->
        <div class="mt-6 bg-white shadow rounded p-4 divide-y divide-gray-200 space-y-4 text-gray-600">
            <!-- single link -->
            <div class="space-y-1 pl-8">
                <a href="{% url 'shop:myaccount' %}" 
                    class="relative text-base font-medium capitalize hover:text-primary transition block text-primary">
                    Manage account
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-address-card"></i>
                    </span>
                </a>
                <a href="{% url 'shop:edit_myaccount' %}" class="hover:text-primary transition capitalize block">Profile
                    information</a>
                <a href="{% url 'shop:myaddress' %}" class="hover:text-primary transition capitalize block">Manage
                    address</a>
                <a href="{% url 'shop:password_change' %}" class="hover:text-primary transition capitalize block">change
                    password</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    My order history
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-gift"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">my returns</a>
                <a href="#" class="hover:text-primary transition block capitalize">my cancellations</a>
                <a href="#" class="hover:text-primary transition block capitalize">my reviews</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    Payment methods
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-credit-card"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">Voucher</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
               <a href="{% url 'shop:wishlist' %}" class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    my wishlist
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-heart"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
                <a href="{% url 'shop:logout' %}"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    logout
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-sign-out-alt"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
        </div>
        <!-- profile links end -->
    </div>
    <!-- sidebar end -->

    <!-- account content -->
    <div class="col-span-9 shadow rounded px-6 pt-5 pb-7 mt-6 lg:mt-0">
        <h3 class="text-lg font-medium capitalize mb-4">
            Profile Information
        </h3>
        <form class="account-form" action="post" action=".">
            <div class="space-y-4">
                <div class="grid sm:grid-cols-2 gap-4">
                    <div>
                        <label class="text-gray-600 mb-2 block">
                            First Name
                        </label>
                        <input name="first_name" class="input-box" value="{{ request.user.first_name }}" type="text">
                    </div>
                    <div>
                        <label class="text-gray-600 mb-2 block">
                            Last Name
                        </label>
                        <input name="last_name" class="input-box" value="{{ request.user.last_name }}" type="text">
                    </div>
                </div>
                <div class="grid sm:grid-cols-2 gap-4">
                    <div>
                        <label class="text-gray-600 mb-2 block">
                            Username
                        </label>
                        <input name="last_name" class="input-box" value="{{ request.user.username }}" type="text">
                    </div>
                    <div>
                        <label class="text-gray-600 mb-2 block">
                            E-mail
                        </label>
                        <input name="last_name" class="input-box" value="{{ request.user.email }}" type="text">
                    </div>
                </div>
            </div>
            <div class="mt-6">
                <button type="submit"
                    class="px-6 py-2 text-center text-white bg-primary border border-primary rounded hover:bg-transparent hover:text-primary transition uppercase font-roboto font-medium">
                    Save changes
                </button>
            </div>
        </form>
    </div>
    <!-- account content end -->
</div>
<!-- account wrapper end -->
{% endblock %}

shop/templates/shop/account/myaccount.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}My account{% endblock %}

{% block content %}
<!-- breadcrum -->
<div class="py-4 container flex gap-3 items-center">
<a href="/" class="text-primary text-base">
    <i class="fas fa-home"></i>
</a>
<span class="text-sm text-gray-400"><i class="fas fa-chevron-right"></i></span>
<p class="text-gray-600 font-medium uppercase">My Account</p>
</div>
<!-- breadcrum end -->

<!-- account wrapper -->
<div class="container lg:grid grid-cols-12 items-start gap-6 pt-4 pb-16">
<!-- sidebar -->
<div class="col-span-3">
    <!-- account profile -->
    <div class="px-4 py-3 shadow flex items-center gap-4">
        <div class="flex-shrink-0">
            <img src="{% static "img/avatar.png" %}"
                class="rounded-full w-14 h-14 p-1 border border-gray-200 object-cover">
        </div>
        <div>
            <p class="text-gray-600">Hello,</p>
            <h4 class="text-gray-800 capitalize font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
        </div>
    </div>
    <!-- account profile end -->

    <!-- profile links -->
    <div class="mt-6 bg-white shadow rounded p-4 divide-y divide-gray-200 space-y-4 text-gray-600">
        <!-- single link -->
        <div class="space-y-1 pl-8">
            <a href="{% url 'shop:myaccount' %}" 
                class="relative text-base font-medium capitalize hover:text-primary transition block text-primary">
                Manage account
                <span class="absolute -left-8 top-0 text-base">
                    <i class="far fa-address-card"></i>
                </span>
            </a>
            <a href="{% url 'shop:edit_myaccount' %}" class="hover:text-primary transition capitalize block">Profile
                information</a>
            <a href="{% url 'shop:myaddress' %}" class="hover:text-primary transition capitalize block">Manage
                address</a>
            <a href="{% url 'shop:password_change' %}" class="hover:text-primary transition capitalize block">change
                password</a>
        </div>
        <!-- single link end -->
        <!-- single link -->
        <div class="space-y-1 pl-8 pt-4">
            <a href="#"
                class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                My order history
                <span class="absolute -left-8 top-0 text-base">
                    <i class="fas fa-gift"></i>
                </span>
            </a>
            <a href="#" class="hover:text-primary transition block capitalize">my returns</a>
            <a href="#" class="hover:text-primary transition block capitalize">my cancellations</a>
            <a href="#" class="hover:text-primary transition block capitalize">my reviews</a>
        </div>
        <!-- single link end -->
        <!-- single link -->
        <div class="space-y-1 pl-8 pt-4">
            <a href="#"
                class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                Payment methods
                <span class="absolute -left-8 top-0 text-base">
                    <i class="far fa-credit-card"></i>
                </span>
            </a>
            <a href="#" class="hover:text-primary transition block capitalize">Voucher</a>
        </div>
        <!-- single link end -->
        <!-- single link -->
        <div class="pl-8 pt-4">
           <a href="{% url 'shop:wishlist' %}" class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                my wishlist
                <span class="absolute -left-8 top-0 text-base">
                    <i class="far fa-heart"></i>
                </span>
            </a>
        </div>
        <!-- single link end -->
        <!-- single link -->
        <div class="pl-8 pt-4">
            <a href="{% url 'shop:logout' %}"
                class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                logout
                <span class="absolute -left-8 top-0 text-base">
                    <i class="fas fa-sign-out-alt"></i>
                </span>
            </a>
        </div>
        <!-- single link end -->
    </div>
    <!-- profile links end -->
</div>
<!-- sidebar end -->

<!-- account content -->
<div class="col-span-9 grid md:grid-cols-3 gap-4 mt-6 lg:mt-0">
    <!-- single card -->
    <div class="shadow rounded bg-white px-4 pt-6 pb-8">
        <div class="flex justify-between items center mb-4">
            <h3 class="font-medium capitalize text-gray-800 text-lg">personal profile</h3>
            <a href="{% url 'shop:edit_myaccount' %}" class="text-primary">Edit</a>
        </div>
        <div class="space-y-1">
            <h4 class="text-gray-700 font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            <p class="text-gray-800">{{ user.email }}</p>
            <p class="text-gray-800">{{ user.username }}</p>
        </div>
    </div>
    <!-- single card end -->
    <!-- single card -->
    <div class="shadow rounded bg-white px-4 pt-6 pb-8">
        <div class="flex justify-between items center mb-4">
            <h3 class="font-medium capitalize text-gray-800 text-lg">Shipping Address</h3>
            <a href="{% url 'shop:myaddress' %}" class="text-primary">Edit</a>
        </div>
        <div class="space-y-1">
            <h4 class="text-gray-700 font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            <p class="text-gray-800">3891 Ranchview Dr.</p>
            <p class="text-gray-800">Richardson, Califora</p>
            <p class="text-gray-800">(123) 456-789</p>
        </div>
    </div>
    <!-- single card end -->
    <!-- single card -->
    <div class="shadow rounded bg-white px-4 pt-6 pb-8">
        <div class="flex justify-between items center mb-4">
            <h3 class="font-medium capitalize text-gray-800 text-lg">Billing Address</h3>
            <a href="#" class="text-primary">Edit</a>
        </div>
        <div class="space-y-1">
            <h4 class="text-gray-700 font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            <p class="text-gray-800">3891 Ranchview Dr.</p>
            <p class="text-gray-800">Richardson, Califora</p>
            <p class="text-gray-800">(123) 456-789</p>
        </div>
    </div>
    <!-- single card end -->
</div>
<!-- account content end -->
</div>
<!-- account wrapper end -->
{% endblock %}

shop/templates/shop/account/user_wish_list.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}Wish List{% endblock %}

{% block content %}
 <!-- breadcrum -->
 <div class="py-4 container flex gap-3 items-center">
    <a href="/" class="text-primary text-base">
        <i class="fas fa-home"></i>
    </a>
    <span class="text-sm text-gray-400"><i class="fas fa-chevron-right"></i></span>
    <p class="text-gray-600 font-medium uppercase">My Account</p>
</div>
<!-- breadcrum end -->

<!-- account wrapper -->
<div class="container lg:grid grid-cols-12 items-start gap-6 pt-4 pb-16">
    <!-- sidebar -->
    <div class="col-span-3">
        <!-- account profile -->
        <div class="px-4 py-3 shadow flex items-center gap-4">
            <div class="flex-shrink-0">
                <img src="{% static "img/avatar.png" %}" class="rounded-full w-14 h-14 p-1 border border-gray-200 object-cover">
            </div>
            <div>
                <p class="text-gray-600">Hello,</p>
                <h4 class="text-gray-800 capitalize font-medium">{{ user.first_name }} {{ user.last_name }}</h4>
            </div>
        </div>
        <!-- account profile end -->

        <!-- profile links -->
        <div class="mt-6 bg-white shadow rounded p-4 divide-y divide-gray-200 space-y-4 text-gray-600">
            <!-- single link -->
            <div class="space-y-1 pl-8">
                <a href="{% url 'shop:myaccount' %}"
                    class="relative text-base font-medium capitalize hover:text-primary transition block">
                    Manage account
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-address-card"></i>
                    </span>
                </a>
                <a href="{% url 'shop:edit_myaccount' %}" class="hover:text-primary transition capitalize block">Profile
                    information</a>
                <a href="{% url 'shop:myaddress' %}" class="hover:text-primary transition capitalize block">Manage
                    address</a>
                <a href="{% url 'shop:password_change' %}" class="hover:text-primary transition capitalize block">change
                    password</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    My order history
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-gift"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">my returns</a>
                <a href="#" class="hover:text-primary transition block capitalize">my cancellations</a>
                <a href="#" class="hover:text-primary transition block capitalize">my reviews</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="space-y-1 pl-8 pt-4">
                <a href="#"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    Payment methods
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-credit-card"></i>
                    </span>
                </a>
                <a href="#" class="hover:text-primary transition block capitalize">Voucher</a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
                <a href="{% url 'shop:wishlist' %}"
                    class="relative medium capitalize font-medium hover:text-primary transition block text-primary">
                    my wishlist
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="far fa-heart"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
            <!-- single link -->
            <div class="pl-8 pt-4">
                <a href="{% url 'shop:logout' %}"
                    class="relative medium capitalize text-gray-800 font-medium hover:text-primary transition block">
                    logout
                    <span class="absolute -left-8 top-0 text-base">
                        <i class="fas fa-sign-out-alt"></i>
                    </span>
                </a>
            </div>
            <!-- single link end -->
        </div>
        <!-- profile links end -->
    </div>
    <!-- sidebar end -->

    <!-- account content -->
    <div class="col-span-9 mt-6 lg:mt-0 space-y-4">
        <!-- single wishlist -->
        <div class="text-center">
            {% if messages %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" alert-{{ message.tags }}" role="alert">
            {% for message in messages  %}
              {{message|safe}} - <a href="{% url "shop:wishlist" %}" class="alert-link">Your Wishlist</a>.
            {% endfor %}
            </div>
            {% endif %}
          </div>
        {% if wishlist %}
            {% for product in wishlist %}
            <div
                class="flex items-center md:justify-between gap-4 md:gap-6 p-4 border border-gray-200 rounded flex-wrap md:flex-nowrap">
                <!-- cart image -->
                <a href="{{ product.get_absolute_url }}">
                    <div class="w-28 flex-shrink-0">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}"  class="w-full">
                    </div>
                </a>
                <!-- cart image end -->
                <!-- cart content -->
                <div class="md:w-1/3 w-full">
                    <h2 class="text-gray-800 mb-1 xl:text-xl textl-lg font-medium uppercase">
                        {{ product.name }}
                    </h2>
                    <p class="text-gray-500 text-sm">Availability: <span class="text-green-600">In Stock</span></p>
                </div>
                <!-- cart content end -->
                <div class="">
                    <p class="text-primary text-lg font-semibold">€{{ product.price }}</p>
                </div>           
                <div class="text-gray-600 hover:text-primary cursor-pointer">
                    <a href="{% url "shop:user_wishlist" product.id %}">
                        <i class="fas fa-trash"></i>
                    </a>
                </div>
            </div>
            <!-- single wishlist end -->
            {% endfor %}
        {% else %}
            <p class="text-center">No products have been added to wishlist yet!</p>
        {% endif %}
    </div>
    <!-- account content end -->
</div>
<!-- account wrapper end -->
{% endblock %}